### ISSUE TITLE
Crash on !devoice xxxx

### ISSUE THREAD

**Issue by Dinnerbone** [Dinnerbone/GrumpyPie#9]
``` javascript
/home/dinnerbone/buttler/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.events.parseUsersChannel.events.leave.events.quit.events.joined.events.kick.events.renamed.events.changeMode (/home/dinnerbone/buttler/core/users.js:67:66)
    at Client.<anonymous> (/home/dinnerbone/buttler/core/core.js:188:26)
    at emitMany (events.js:121:13)
    at Client.emit (events.js:195:7)
    at /home/dinnerbone/buttler/node_modules/irc/lib/irc.js:316:30
    at Array.forEach (native)
    at Client.<anonymous> (/home/dinnerbone/buttler/node_modules/irc/lib/irc.js:270:26)
    at emitOne (events.js:90:13)
    at Client.emit (events.js:182:7)
    at iterator (/home/dinnerbone/buttler/node_modules/irc/lib/irc.js:846:26)
```

**Comment by Mustek** [comment]
Can't reproduce...
At which time was this?

**Comment by Dinnerbone** [comment]
https://gist.githubusercontent.com/anonymous/07c783a9a5862c4eb3e2a57a77b86243/raw/c98b4256fbac08a528aeac2e7abe505b7470823a/results.txt
